version: 2.1
orbs: 
  terraform: circleci/terraform@3.0.1

parameters:
  docker_image:
     type: string
     default: mijack/circleci-test-image

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          working_directory: terraform/
