version: 2.1

parameters:
  docker_image:
     type: string
     default: mijack/circleci-test-image
#########
### Executors
#########
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.1.8

  awscli:
    docker:
      - image: amazon/aws-cli
#########
### commands
#########
commands:
  terraform_plan:
    steps:
      - run:
          name: terraform init and plan
          working_directory: ./terraform
          command: |
            terraform init && terraform plan
  terraform_apply:
    steps:
      - run:
          name: terraform init and apply
          working_directory: ./terraform
          command: |
            terraform init && terraform apply --auto-approve

  terraform_destroy:
    steps:
      - run:
          name: terraform init and destroy
          working_directory: ./terraform
          command: |
            terraform init && terraform apply --force --destroy
  deploy_ec2:
    steps:
      - run:
          name: sts get caller identity
          command: |
            aws sts get-caller-identity
                     
  docker_login:
    steps:
      - run:
          name: docker login
          command: |
            docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_PASSWORD}
  build_image:
    steps:
      - run:
          name: docker build
          command: |
            docker build -t circleci-test-image:latest .
            docker tag circleci-test-image:latest mijack/circleci-test-image:latest
  push_image:
    steps:
      - run:
          name: docker push
          command: |
            docker push mijack/circleci-test-image:latest 
                     

#########
### jobs
#########

jobs:
  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - terraform_plan
  terraform_apply:
    executor: terraform
    steps:
      - checkout
      - terraform_apply

  terraform_destroy:
    executor: terraform
    steps:
      - checkout
      - terraform_destroy

  deploy_application:
    executor: awscli
    steps:
      - deploy_ec2
  prepare_docker_image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - docker_login
      - build_image
      - push_image

      
      

          
#########
### Workflows
#########
workflows:
  "deploy_and_delete":
    jobs:
      - prepare_docker_image:
          context: aws-access

      - deploy_application:
          type: approval
          context: aws-access
      
      - terraform_plan:
          context: aws-access

      - terraform_apply_approve:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          context: aws-access
          requires:
            - terraform_apply_approve

      - terraform_destroy_approve:
          type: approval
          requires:
            - terraform_apply          


      - terraform_destroy:
          requires:
            - terraform_destroy_approve  
          context: aws-access
